#!/usr/bin/env python3
"""
calibrate_odom.py -- one-shot, offline: measure the mecanum-drive odometry
scale error against Gazebo ground truth and write config/odom_scale.yaml.

Runs three open-loop moves on /cmd_vel_key (through the same mux as teleop),
each bracketed by a settle, and compares the ground-truth displacement
(/gt/dynamic_pose, bridged from /world/warehouse/dynamic_pose/info) with the
reported /odom/wheel displacement:

  forward  : k_vx   = gt_dx  / odo_dx
  strafe   : k_vy   = gt_dy  / odo_dy
  rotate   : k_vyaw = gt_dyaw / odo_dyaw

Prereqs: warehouse_sim.launch.py running headless, plus the truth bridge:
  ros2 run ros_gz_bridge parameter_bridge --ros-args \
      -p config_file:=<pkg>/share/holonomic_nav/config/truth_bridge.yaml

    ros2 run holonomic_nav calibrate_odom.py --ros-args -p out:=<pkg-src>/config/odom_scale.yaml
"""

import math
import time

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from tf2_msgs.msg import TFMessage


def _yaw(q):
    return math.atan2(2.0 * (q.w * q.z + q.x * q.y),
                      1.0 - 2.0 * (q.y * q.y + q.z * q.z))


class Calib(Node):
    def __init__(self):
        super().__init__("calibrate_odom")
        self.declare_parameter("out", "/tmp/odom_scale.yaml")
        self.declare_parameter("speed", 1.2)      # calibrate at the mapping cruise speed
        self.declare_parameter("move_time", 8.0)
        self.declare_parameter("ramp", 1.5)       # discard this much lead-in per leg
        self.declare_parameter("reps", 2)
        self.declare_parameter("gt_index", 0)  # transforms[0] = model root on dynamic_pose
        self.out = self.get_parameter("out").value
        self.speed = float(self.get_parameter("speed").value)
        self.move_time = float(self.get_parameter("move_time").value)
        self.ramp = float(self.get_parameter("ramp").value)
        self.reps = int(self.get_parameter("reps").value)
        self.gt_idx = int(self.get_parameter("gt_index").value)

        self.gt = None
        self.odo = None
        self.pub = self.create_publisher(Twist, "/cmd_vel_key", 10)
        self.create_subscription(TFMessage, "/gt/dynamic_pose", self._gt_cb, 20)
        self.create_subscription(Odometry, "/odom/wheel", self._odo_cb, 20)

    def _gt_cb(self, msg: TFMessage):
        if len(msg.transforms) > self.gt_idx:
            tr = msg.transforms[self.gt_idx]
            t, r = tr.transform.translation, tr.transform.rotation
            self.gt = (t.x, t.y, _yaw(r))

    def _odo_cb(self, m: Odometry):
        p, q = m.pose.pose.position, m.pose.pose.orientation
        self.odo = (p.x, p.y, _yaw(q))

    def _spin(self, sec):
        t0 = time.time()
        while time.time() - t0 < sec and rclpy.ok():
            rclpy.spin_once(self, timeout_sec=0.05)

    def _wait_ready(self):
        while (self.gt is None or self.odo is None) and rclpy.ok():
            rclpy.spin_once(self, timeout_sec=0.2)

    def _drive(self, tw: Twist, sec):
        t0 = time.time()
        while time.time() - t0 < sec and rclpy.ok():
            self.pub.publish(tw)
            rclpy.spin_once(self, timeout_sec=0.05)

    def run(self):
        self._wait_ready()
        self._spin(1.0)

        def _delta(g0, g1, o0, o1, comp):
            if comp == "yaw":
                dg = math.atan2(math.sin(g1[2] - g0[2]), math.cos(g1[2] - g0[2]))
                do = math.atan2(math.sin(o1[2] - o0[2]), math.cos(o1[2] - o0[2]))
            else:
                dg = math.hypot(g1[0] - g0[0], g1[1] - g0[1])
                do = math.hypot(o1[0] - o0[0], o1[1] - o0[1])
            return dg, do

        def leg(tw, comp):
            ks = []
            for _ in range(self.reps):
                self._drive(tw, self.ramp)          # accelerate, discard
                g0, o0 = self.gt, self.odo
                self._drive(tw, self.move_time)     # steady segment -- measure this
                g1, o1 = self.gt, self.odo
                self.pub.publish(Twist()); self._spin(2.0)   # settle before next rep
                dg, do = _delta(g0, g1, o0, o1, comp)
                k = dg / do if abs(do) > 1e-4 else 1.0
                ks.append(k)
                print(f"    {comp} rep: gt {dg:+.3f}  odo {do:+.3f}  k={k:.4f}", flush=True)
            return sum(ks) / len(ks)

        fx = Twist(); fx.linear.x = self.speed
        fy = Twist(); fy.linear.y = self.speed
        fz = Twist(); fz.angular.z = self.speed

        print("calibrating: forward ...", flush=True)
        k_vx = leg(fx, "x")
        print("calibrating: strafe ...", flush=True)
        k_vy = leg(fy, "y")
        print("calibrating: rotate ...", flush=True)
        k_vyaw = leg(fz, "yaw")

        with open(self.out, "w") as fh:
            fh.write("# generated by calibrate_odom.py -- mecanum odometry scale\n")
            fh.write("odom_correction_node:\n  ros__parameters:\n")
            fh.write(f"    k_vx: {k_vx:.4f}\n    k_vy: {k_vy:.4f}\n    k_vyaw: {k_vyaw:.4f}\n")
        print(f"wrote {self.out}: k_vx={k_vx:.4f} k_vy={k_vy:.4f} k_vyaw={k_vyaw:.4f}", flush=True)
        worst = max(abs(k_vx - 1), abs(k_vy - 1), abs(k_vyaw - 1))
        print(f"worst-axis error {100*worst:.1f}%  "
              f"({'ENABLE the correction node' if worst > 0.02 else 'below 2% -- correction optional'})",
              flush=True)


def main():
    rclpy.init()
    node = Calib()
    try:
        node.run()
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
